[project]
name = "streaming-agent-service"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Camilovelez1", email = "camilo95022@gmail.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
